# Generated by Django 6.0.7 on 2026-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile_role_alter_hub_id_alter_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
