# Generated by Django 6.0.7 on 2026-07-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userprofile_is_verified_userprofile_otp_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
    ]
