# Generated by Django 6.0.7 on 2026-08-07 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0003_userprofile_full_name_can_create_hubs_admincode_directconversation",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininvitationcode",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who created this code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invitation_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="admininvitationcode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="admininvitationcode",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who redeemed this code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_invitation_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="directconversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="directconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_1", models.F("user_2")), _negated=True),
                name="direct_conversation_distinct_users",
            ),
        ),
    ]
