# Generated by Django 6.0.7 on 2026-08-08 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_admininvitationcode_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("announcements", "Announcements"),
                            ("resources", "Resources"),
                            ("meetings", "Meetings"),
                            ("tasks", "Tasks"),
                        ],
                        help_text="Type of content this section contains",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display name for this section (e.g., 'Class Updates', 'Assignments')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description explaining what this section is for",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this section is visible to Hub members",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.ForeignKey(
                        help_text="The Hub this section belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="api.hub",
                    ),
                ),
            ],
            options={
                "ordering": ["hub", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["hub", "is_enabled"],
                        name="api_hubsect_hub_id_0ebfad_idx",
                    ),
                    models.Index(
                        fields=["hub", "order"], name="api_hubsect_hub_id_66eacc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hub", "section_type"), name="unique_hub_section_type"
                    )
                ],
            },
        ),
    ]
