# Generated by Django 6.0.7 on 2026-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_broadcast_resource_taskitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Public handle chosen during profile setup",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="E.164 number used for OTP delivery",
                max_length=20,
                null=True,
            ),
        ),
    ]
