# Generated by Django 6.0.7 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_smsdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsdelivery",
            name="provider_status",
            field=models.CharField(
                blank=True,
                help_text="Raw delivery status from Arkesel webhook (e.g. DELIVERED).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="smsdelivery",
            name="provider_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
