# Generated by Django 6.0.7 on 2026-08-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_smsdelivery_provider_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broadcasts",
                to="api.hub",
            ),
        ),
        migrations.AlterField(
            model_name="smsdelivery",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_deliveries",
                to="api.message",
            ),
        ),
        migrations.AddField(
            model_name="smsdelivery",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_deliveries",
                to="api.broadcast",
            ),
        ),
        migrations.AddConstraint(
            model_name="smsdelivery",
            constraint=models.CheckConstraint(
                condition=(
                    (models.Q(message__isnull=False) & models.Q(broadcast__isnull=True))
                    | (models.Q(message__isnull=True) & models.Q(broadcast__isnull=False))
                ),
                name="smsdelivery_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="smsdelivery",
            index=models.Index(
                fields=["broadcast", "status"],
                name="api_smsdeli_broadca_6f3f69_idx",
            ),
        ),
    ]
