# Generated by Django 6.0.7 on 2026-08-11 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_broadcast_hub_smsdelivery_broadcast"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HubMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("meeting_url", models.URLField(max_length=1000)),
                ("scheduled_for", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scheduled_for", "id"],
            },
        ),
        migrations.RenameIndex(
            model_name="smsdelivery",
            new_name="api_smsdeli_message_616637_idx",
            old_name="api_smsdeli_message_status_idx",
        ),
        migrations.RenameIndex(
            model_name="smsdelivery",
            new_name="api_smsdeli_broadca_65b972_idx",
            old_name="api_smsdeli_broadca_6f3f69_idx",
        ),
        migrations.RenameIndex(
            model_name="smsdelivery",
            new_name="api_smsdeli_recipie_28d77d_idx",
            old_name="api_smsdeli_recipient_status_idx",
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("document", "Document"),
                    ("video", "Video"),
                    ("link", "Link"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="hubmeeting",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_hub_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hubmeeting",
            name="hub",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="api.hub",
            ),
        ),
        migrations.AddIndex(
            model_name="hubmeeting",
            index=models.Index(
                fields=["hub", "scheduled_for"], name="api_hubmeet_hub_id_62f3ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hubmeeting",
            index=models.Index(
                fields=["hub", "created_at"], name="api_hubmeet_hub_id_1558ac_idx"
            ),
        ),
    ]
