# Generated by Django 6.0.7 on 2026-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_hub_is_premium_hub_sms_credits_smscredittransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="broadcasts/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="broadcasts/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="hubmeeting",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="resources/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="broadcasts/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="resources/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="tasks/attachments/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="taskitem",
            name="submission_file",
            field=models.FileField(
                blank=True, null=True, upload_to="tasks/submissions/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="hubmeeting",
            name="meeting_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
